@base_address = http://localhost:5054/api/tasks

GET {{base_address}}/2003
Accept: application/json

###
GET {{base_address}}?SortBy=deadline&SortDirection=desc

###
POST {{base_address}}
Content-Type: application/json

{
  "TaskHeaderId": 1,
  "TaskTitle": "Video on global exception handling",
  "TaskUri": null,
  "TaskPriorityId": 2,
  "Deadline": null,
  "ScheduledAt": null,
  "DisplayAtBoard":true,
  "SubTasks": [
    {
      "SubTaskTitle": "Edit video",
      "SubTaskUri": null
    }
  ],
  "Tags": [
    "blog",
    "angular",
    "programming"
  ]
}

###
PUT {{base_address}}/2003
Content-Type: application/json

{
  "TaskId":2003,
  "TaskHeaderId": 1,
  "TaskTitle": "Create a video on global exception handling",
  "TaskUri": null,
  "TaskPriorityId": 3,
  "TaskStatusId": 2,
  "Deadline": "2025-05-25T15:18:20",
  "ScheduledAt": null,
  "DisplayAtBoard":true,
  "SubTasks": [
    {
      "SubTaskId":2004,
      "SubTaskTitle": "Edit the video",
      "SubTaskUri": null
    },
    {
      "SubTaskId":2008,
      "SubTaskTitle": "Make a thumnail for this video",
      "SubTaskUri": null
    },
    {
      "SubTaskId":2009,
      "SubTaskTitle": "Post this video in a Youtube",
      "SubTaskUri": null
    }
  ],
  "Tags": [
    "video",
    "dotnet",
    "programming"
  ]
}

###
DELETE  {{base_address}}/2002

###
GET http://localhost:5054/api/tags
