@base_address = http://localhost:5054/api/tasks

GET {{base_address}}/1
Accept: application/json

###
POST {{base_address}}
Content-Type: application/json

{
  "TaskHeaderId": 1,
  "TaskTitle": "Video on global exception handling",
  "TaskUri": null,
  "TaskPriorityId": 2,
  "TaskStatusId": 1,
  "Deadline": null,
  "ScheduledAt": null,
  "DisplayAtBoard":true,
  "SubTasks": [
    {
      "SubTaskTitle": "Edit video",
      "SubTaskUri": null
    }
  ],
  "Tags": [
    "blog",
    "angular",
    "programming"
  ]
}

###
GET http://localhost:5054/api/tags

###
DELETE  {{base_address}}/2002