@base_address = http://localhost:5054

POST {{base_address}}/api/trackentries
Content-Type: application/json

{
  "entryDate": "2025-03-23",
  "sleptAt": "2025-03-23T03:15",
  "wokeUpAt": "2025-03-23T07:45",
  "napInMinutes": 0,
  "totalWorkInMinutes": 0,
  "remarks": null
}

###

GET {{base_address}}/api/trackentries?limit=10&sortDirection=ASC

Accept: application/json

###

GET {{base_address}}/api/trackentries/14
Accept: application/json

###

PUT {{base_address}}/api/trackentries/57
Content-Type: application/json

{
  "trackEntryId": 57,
  "entryDate": "2025-03-23",
  "sleptAt": "2025-03-23T03:15",
  "wokeUpAt": "2025-03-23T07:45",
  "napInMinutes": 0,
  "totalWorkInMinutes": 0,
  "remarks": "adfasdf"
}
###
DELETE {{base_address}}/api/trackentries/14

### Bulk insert : track entries
POST {{base_address}}/bulk-track-entries