@base_address = http://localhost:5054/api/task-headers
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJqdGkiOiJmNzgzMDE4OC03MWMwLTQ4Y2MtYjBiNi1mNjIwYmM1MjQzZDYiLCJuYmYiOjE3NDgxNzQ5NDUsImV4cCI6MTc0ODE3Njc0NSwiaWF0IjoxNzQ4MTc0OTQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.L54PMFXnOVRzAln3RebySieZeX3IlNYQhdn9PBbCJds

GET {{base_address}}
Authorization: Bearer {{token}}

###
GET {{base_address}}/68aebce9fe35dfd9c75d1286

###
POST {{base_address}}
Content-Type: application/json

{
    "taskHeaderTitle":"Blah 2ddd",
    "sortOrder":1
}

###
DELETE {{base_address}}/68aebce9fe35dfd9c75d1286

###
PUT {{base_address}}/68aebce9fe35dfd9c75d1286 HTTP/1.1
Content-Type: application/json

{
    "taskHeaderId":"68aebce9fe35dfd9c75d1286",
    "taskHeaderTitle":"blah blah blah",
    "sortOrder":2
}