@base_address = http://localhost:5054/api/tasks
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJqdGkiOiJmNzgzMDE4OC03MWMwLTQ4Y2MtYjBiNi1mNjIwYmM1MjQzZDYiLCJuYmYiOjE3NDgxNzQ5NDUsImV4cCI6MTc0ODE3Njc0NSwiaWF0IjoxNzQ4MTc0OTQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.L54PMFXnOVRzAln3RebySieZeX3IlNYQhdn9PBbCJds

# Get by id
GET {{base_address}}/68ada389f15d01a9d910094a
Accept: application/json
Authorization: Bearer {{token}}

# TODO: no filters are working
### Get all 
GET {{base_address}}?SortBy=ScheduledAt&SortDirection=

### Display board tasks
GET {{base_address}}/displayboard-tasks

###
GET {{base_address}}/statuses

###
GET {{base_address}}/priorities

###
POST {{base_address}}
Content-Type: application/json

{
  "TaskHeaderId": "68ac482c1867c4f34789b03f",
  "TaskTitle": "temp",
  "TaskUri": "htttp://blah.com",
  "TaskPriorityId": 2,
  "TaskStatusId": 1,
  "Deadline": null,
  "ScheduledAt": null,
  "DisplayAtBoard":false,
  "SubTasks": [
    {
      "SubTaskTitle": "Write a blog post",
      "SubTaskUri": "http://azure.xyx/get/xfs/dee"
    },
    {
      "SubTaskTitle": "Schedule it on medium.com",
      "SubTaskUri": null
    }
  ],
  "Tags": "blog,azure,chsharp"
  }

###
PUT {{base_address}}/68ad61d9ac43edf9b40985bd
Content-Type: application/json

{
  "TaskId":"68ad61d9ac43edf9b40985bd",
  "TaskHeaderId": "68ac482c1867c4f34789b03f",
  "TaskTitle": "Create a blog post on azure blob storage",
  "TaskUri": "htttp://blahh.com",
  "TaskPriorityId": 2,
  "TaskStatusId": 1,
  "Deadline": null,
  "ScheduledAt": null,
  "DisplayAtBoard":false,
  "SubTasks": [
    {
      "SubTaskId": "7f995b0d-0840-425b-9ee2-4fffdc8c2c3f",
      "SubTaskTitle": "Write a blog post",
      "SubTaskUri": "http://azure.xyx/get/xfs/dee"
    },
    {
      "SubTaskId":"c5b151b4-0427-4922-8d91-1836bb64b161",
      "SubTaskTitle": "Post at ravindradevrani.com and Schedule it on medium.com",
      "SubTaskUri": null
    }
  ],
  "Tags": "blog,azure,dotnet"
  }

###
DELETE  {{base_address}}/68ada389f15d01a9d910094a

###
GET http://localhost:5054/api/tags
