@base_address = http://localhost:5054
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJqdGkiOiI2MWZiYzQyMy02NzY1LTQ3MWMtYjkwMy03ZjdhMmJlMjliOTEiLCJuYmYiOjE3NDgxNzUyNDUsImV4cCI6MTc0ODE3NzA0NSwiaWF0IjoxNzQ4MTc1MjQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.1YVtnPnwBmozDNCetvha6sOCTjDnMoQA0ekOHZfbO0g

POST {{base_address}}/api/trackentries
Content-Type: application/json

{
  "entryDate": "2025-03-27T02:50",
  "sleptAt": "2025-03-27T22:00",
  "wokeUpAt": "2025-03-25T06:30",
  "napInMinutes": 0,
  "totalWorkInMinutes": 360,
  "remarks": null
}

### Get list
GET {{base_address}}/api/trackentries
Accept: application/json

### GET List Filtered
GET {{base_address}}/api/trackentries?startDate=2025-03-24&endDate=2025-03-26
Accept: application/json
Authorization: Bearer {{token}}

### GET One
GET {{base_address}}/api/trackentries/68abe9213b383748dc68588c
Accept: application/json

### PUT
PUT {{base_address}}/api/trackentries/68abeb003b383748dc68588d
Content-Type: application/json

{
  "trackEntryId":"68abeb003b383748dc68588d",
  "entryDate": "2025-03-27T02:50",
  "sleptAt": "2025-03-27T22:00",
  "wokeUpAt": "2025-03-28T06:30",
  "napInMinutes": 0,
  "totalWorkInMinutes": 360,
  "remarks": null
}

### Delete
DELETE {{base_address}}/api/trackentries/68aaf7d23c50de7c2d44cef6

### Bulk insert : track entries
POST {{base_address}}/bulk-track-entries