@base_address = http://localhost:5054
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJqdGkiOiI2MWZiYzQyMy02NzY1LTQ3MWMtYjkwMy03ZjdhMmJlMjliOTEiLCJuYmYiOjE3NDgxNzUyNDUsImV4cCI6MTc0ODE3NzA0NSwiaWF0IjoxNzQ4MTc1MjQ1LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.1YVtnPnwBmozDNCetvha6sOCTjDnMoQA0ekOHZfbO0g

POST {{base_address}}/api/trackentries
Content-Type: application/json

{
  "entryDate": "2025-03-23",
  "sleptAt": "2025-03-23T03:15",
  "wokeUpAt": "2025-03-23T07:45",
  "napInMinutes": 0,
  "totalWorkInMinutes": 0,
  "remarks": null
}

###
GET {{base_address}}/api/trackentries?limit=3&sortDirection=ASC&pageDirection=prev&lastEntryDate=2025-02-16
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{base_address}}/api/trackentries/1001
Accept: application/json

###
PUT {{base_address}}/api/trackentries/1001
Content-Type: application/json

{
 "trackEntryId": 1001,
 "entryDate": "2025-04-28",
 "sleptAt": "2025-04-28T00:10:00.000Z",
 "wokeUpAt": "2025-04-28T21:00:00.000Z",
 "napInMinutes": 0,
 "totalWorkInMinutes": 194,
 "remarks": null
 }

###
DELETE {{base_address}}/api/trackentries/14

### Bulk insert : track entries
POST {{base_address}}/bulk-track-entries